New log file opened at Tue Jan 17 10:08:21 CET 2017 by 4156@Besitzer-PC
Taking next connection to: 49499
New client attempting to connect on port: 49500-49499
  Address = /172.20.128.164:49499
This client on port 49500 has uuid 034332e3-26b6-4534-bbdd-2ec853d52cfd configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-034332e3-26b6-4534-bbdd-2ec853d52cfd
Taking next connection to: 49499
New client attempting to connect on port: 49501-49499
  Address = /172.20.128.164:49499
Handshake exception on socket: 49501
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49499
New client attempting to connect on port: 49502-49499
  Address = /172.20.128.164:49499
This client on port 49502 has uuid 4a69703a-2537-488c-a76f-59a3151e2304 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-034332e3-26b6-4534-bbdd-2ec853d52cfd, activator-4a69703a-2537-488c-a76f-59a3151e2304
Taking next connection to: 49499
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49499
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49499
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49499
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49499
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49499
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49499
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49499
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49499
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49499
New client attempting to connect on port: 50673-49499
  Address = /172.20.128.164:49499
Handshake exception on socket: 50673
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49499
New client attempting to connect on port: 50674-49499
  Address = /172.20.128.164:49499
This client on port 50674 has uuid 7a981b08-cad0-4d1a-849b-bb7a82e8f1e3 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-4a69703a-2537-488c-a76f-59a3151e2304, play-fork-run-7a981b08-cad0-4d1a-849b-bb7a82e8f1e3
Taking next connection to: 49499
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49499
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49499
